# .github/workflows/ci.yml
name: Vite CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # adjust based on your project

      - name: Install Dependencies
        run: npm ci # or yarn install / pnpm install

      - name: Build Vite App
        run: npm run build # or your custom build script
